### ISSUE TITLE
Failed to install gatsby-remark-vscode on windows 10 with python 3.7.3

### ISSUE THREAD

**Issue by chivandikwa** [andrewbranch/gatsby-remark-vscode#24] opened 2019-06-06 20:29 UTC
I failed to execute
```
npm install --save gatsby-remark-vscode
```
with Python 3.7.3 installed on a Windows 10 machine. I got an error about 
```
oniguruma > node-gyp rebuild configure error
```
On unistalling that version of python and replacing it with 2.7.16 was I only able to get this to work. By that time I also had to execute
```
npm install --global --production windows-build-tools
```
not sure if the windows-build-tools where necessary as I have Visual Studio 2017 installed with the required C++ dependencies also.

**Comment by andrewbranch** [comment] 2019-06-07 16:02
Hm, interesting. I’m running macOS Mojave with Python 2.7.10. I’m not sure there’s anything we can do about this, but I’ll leave the issue open for visibility. Thanks!

**Comment by chadly** [comment] 2019-08-14 19:52
I'm also having a lot of trouble trying to install this package on Windows. The `oniguruma` package is the one that tries to use node-gyp to use python to compile something in C++ it looks like. I don't have the right incantation of python/C++ versions on my machine for it to work.

Is this package even necessary? Doesn't seem like it is used in this codebase unless it is a peer dependency for something.

**Comment by JCQuintas** [comment] 2019-08-19 22:54
I'm on W10 running Ubuntu on WSL

got `python 2.7.15+` and everything seems to install fine, but tests fail with:

```
ENOENT: no such file or directory, open '/c/gatsby-remark-vscode/test/test.md/Default Dark+'
```

It seems `test.md` is missing? But if I add a file the error changes to `ENOTDIR`...

**Comment by chadly** [comment] 2019-08-21 19:15
> Is this package even necessary?

I see that [`vscode-textmate`](https://github.com/Microsoft/vscode-textmate) depends on `oniguruma` so nevermind on that option of removing it. 😢

**Comment by andrewbranch** [comment] 2019-08-21 19:51
There is an alternative; there’s a [web assembly port](https://github.com/NeekSandhu/onigasm) which also works on Node, it’s just slower. Performance isn’t critical per se since it doesn’t actually affect your gatsby site as it runs, but I’m still loathe to slow down _building_ everyone’s gatsby site since the native version _should_ work. It would be nice if users could opt into the slower WASM version if needed, but I haven’t given a lot of thought about how to accomplish this without requiring an extra step for all users. My only idea so far is to automate publishing an alternate package that uses the WASM version, under the name `gatsby-remark-vscode-wasm` or something. Not sure how much infrastructure that would require.

**Comment by andrewbranch** [comment] 2020-05-04 02:53
I haven’t heard any more complaints about this, and since I was never able to track down the cause in the first place, I don’t think it’s actionable. I’m going to close this, but if anyone subscribed is still having issues, I’d love to hear about it.

**Closed by andrewbranch** 2020-05-04 02:53 UTC

**Comment by chadly** [comment] 2020-05-04 13:13
I stopped complaining because I switched my main development box to Debian :wink:
